name: Release API Patch

on:
  pull_request:
    types:
      - "closed"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout application
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure git email
        run:
          git config --global user.email "mikoajw20@gmail.com"

      - name: Configure git user name
        run:
          git config --global user.name "Miko≈Çaj Wargowski"

      - name: release patch
        if: ${{ github.event.pull_request.merged }} && ${{contains(github.base_ref, 'hotfix')}}
        run: |
          npm install
          npm run release -- patch --ci

      - name: release minor
        if: ${{ github.event.pull_request.merged }} && ${{contains(github.base_ref, 'feature')}}
        run: |
          npm install
          npm run release -- minor --ci


